### ISSUE TITLE
контактные данные

### ISSUE THREAD

**Issue by soveckyFonarik** [Leveofan97/Pmdr#1]

**Comment by soveckyFonarik** [comment]
test

**Comment by Leveofan97** [comment]
Добрый день
А где вы нашли мое резюме ?
В нем вроде как есть телефон и почта

  
>Понедельник, 16 августа 2021, 15:45 +03:00 от Mikhail Pogorelovsky ***@***.***>:
> 
> 
>добрый день.
>к нам прилетело ваше резюме
>можно ваши контактные данные для дальнейшего общения ?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
--
Андрей Корепанов
